dist: trusty
sudo: required

services:
  - docker

env:
  global:
    - RELEASE_VERSION=1.0.0-beta.4
    - BINTRAY_API_KEY="brMQbxFWeVGy4dAng9unaaFRDMV5g/BJP9AtL8elFIkyD1w+KxhaLqJOK7ZC1fe2JzNDL8L9IHkbJ7Vp67sYToUw4W9Ns+46AGPePIQFl85fm5gXCw8y5V30hbJmhfvxf7USugMHbSFHtNEhZHuQP5ZFv622akXjmYCC0VKtmm4="

  matrix:
    - DISTRO=centos
      VERSION=7

    - DISTRO=ubuntu
      VERSION=trusty

    - DISTRO=ubuntu
      VERSION=wily

    - DISTRO=ubuntu
      VERSION=xenial

    - DISTRO=debian
      VERSION=jessie

script:
  - chmod +x linux.sh
  - ./linux.sh $DISTRO $VERSION "$RELEASE_VERSION"
