sudo: true
language: node_js

before_install:
  - gem install fpm --conservative || echo "FPM install failed"
  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then
      if [ "$CC" == "gcc" ]; then
        export CC=$(ls -t /usr/local/bin/gcc-?.?);
      fi
    fi
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then
      export CXX=g++-4.8;
    fi

compiler:
  - gcc
  - clang

node_js:
  - "6.11"

env:
  - DEFAULT_DELAY: 50

matrix:
  include:
    - node_js: "6.11"
      os: osx

script:
  # This fails on node 4
  - if [[ "$TRAVIS_NODE_VERSION" == "6.11"* ]]; then
      npm run lint;
    fi
  - npm run reporter
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then
      sh scripts/run-e2e.sh;
    fi
  # This has to happen here and not in before_deploy to be put in travis cache
  - bash ./scripts/package.sh

cache:
  directories:
    - nexe_node

deploy:
  - provider: s3
    access_key_id:
      secure: "uUtBOO5zd9cFveQ2DK0qqcz+MrpM8F6B4Byz3AZK3biXQJ/IUFys7zmBpJeEPS4W82ch2vbDNE9TPr1GXEb2V3rO9sjwiEHOFTFCxJA0eOXwUDIcRerw/WmT5d9AuMIy0cB6mry6bv0/iioSZndxCvxN6IkVnlyF2XVFVbePHF/jVM28uZlxpSzQzSDRob+r1hqX0yRL0oMi5RlEd/w/7KKW1whouSRobHuZtFGccAqFLTOX1dPM9MhG008rLQ1FA9Q//+yHEV+WFPbcJOuhpMHJBTRX5wAa3nAzh9ik07WWID1aHyUZlLB92kdt0BRM9Vv5DbABgUu5RMcURyYqil2LlRxNGTYYi5TEywefqODfGb8xcWr2kND+m5JztGfSrekWRLaohnqrdbNYsuEGBQ4fV/1jZXatfexbZNBdqcaKy/Qxk3fnKN8L357MeD4RgW4m7c6HNcDXAqFQT4AjUKzjl7LyNSuzmNQsZyevPas2CYAr3Ij1VbzSZQjqYI7N61CtG7IfEMluurBPOt4wuEHyIRgVijmCvqvwuGm5aQpSsoCrkNX0FblMsK6m4nQeCSLGjYleUR6HF/HoWLhydgl5hMKUKQFQF5zgrrXofp3a9Gp7ac6Jz/f6yKjXScWMXawW4UXQBkPg9vaqWdRLCDEYKTL7ReC0RuZAL/jslh4="
    secret_access_key:
      secure: "C3N9EahvzqqDMuT1fWm0jyh5mWW7avHuf2X1vVPwrZrTZJT3Cg2CIUt+m2TVo0imq1tFxaQnpldHoJWx7AgAGpzG4TFshCUZDUX7yK/aD4ySfovjhH4PKeHiFx6FwnplTGyYmyo901aeqD+o6bmpNld4yMMzbyQf8eXX37RxHUN/MRnH3XDnmjaEAF/yVh9/yyzJHp3uWb1/8TrjMzyWwDpp/vsry6RAL6zh6i5LI6Fs7qSlGKB4XYTpI3bTaW25yFACpNunBu9rIFipRprYsFMN7TwybQ7NpI7TfO1VCC/cLAr36C4rel8j+fS4wK6nwZ4M5pI6S9+UmB43hklFMyDOREFmnuem7sRIjlBtUEz303UmMKwVUTwu+OfAxF60aYlNnJatCrFhI2QyPiw0SaKTaa9kHBdUHd4EfH4F6AZUp9nE4PocQFNHxjS6D8IddLYgRFEeMrdOnFLI/fthu6YyABX/9GL9z9Di60EeQSf0favSqSbc4F6q/+vypdLfCnXjnNkiqdd8gixnBVJ8gFbsgC0kmnYc72FJzySaTdsSxHOKKJEVZ7OBYzG2LiC3rjfYXkpB3xnRc20ngzxMQanuq1ylVHyNcFFgn6bRMgzXd/u1O10LyTtDqndNaatRx74dvLJMeRSa6jFX/WiANNBeIHjqNlk2sVrXjCoGatY="
    bucket: ds-server-artifacts
    skip_cleanup: true
    acl: public_read
    local_dir: build
    upload-dir: $TRAVIS_REPO_SLUG
    region: us-east-1
    on:
      branch: master
  - provider: s3
    access_key_id:
      secure: "J15ZeoFnAX5ZrTUm3shyx/azvdtTEfqgI+88I90iHWvpGhzjbympCidD2AglabsgBW8IeS5ieW8QZcRNuGW2IWiakGilI4cMUlAa5gvoSyk+GW/VaPh6CMbFgbMzeg4tEUsBCaxMzFdlKDHPm9vpM+pNa1Qw1Zvxnx9ESk8A7IJElkm0/sdaLLzGhM8cjzd0JIAmRiwo3U5MEaBVkGBsGnXrtuK3MsUe2y5PKjwikBuWfREdK+iTZUbp6tmO3T7AXST3q+qNlo1k1g5JWct9zXMu9rcvpVj2cwjlp2zFuukCTxJff66n5haWm4l5cB8aKj7xdynSi7fpXsnuX11tMfM8LY/ddX+SXjO2DO92/Lw9xVmoAF/M5sj15S9SaVeByuj4e7vqKxB5sGaij3xWo2R709SUZhdYJi3XhlwFIg8FqSooWUvJ5dAgD3Q3YRKbSzo/Kj4478H71obkOwOAlNUhQlwPZUzuI9VvPKLT53+SA4xOx3yJEJpAZDUQk9bdcxnX/CrnL+JDJmua4CdDF1VukhWcF94hlRs3Ln+4wyG6gb3hNrR5BjceM8Ylepa2tw2joL8OxQz+YM0pRS4N9aibZRcdUPJNH9e6nsdRCunIs7TqgbjZ5qLFFP/Y+TJgXLrJNHCLVC9bDr1OkScDeRQp09IJOgfnPgfpsS4rCNo="
    secret_access_key:
      secure: "BhYq5bZHoJn6USKrGsjqFW5JwKNvdq0IdjvBlQmnt4YfDiOEk4gE59ZTWb9jKBj1C4ch5HoPIg7Mkm57mYqQrNC1hsYlfScrPwPKTBz0vOHHarL4NvDcs/5BP8E0oYRASVtcQ/aiwlozRnM8dS1HgSAttk6WubHHg1qeYdxZJ+tPWA03BpXdXw/17caTXMZrwTZn8oH8fj6d4LY77CfgKbIPfuCc5oVvjR7x5lKTFsXDWwFxz68/37LHvWNCfgu3QFxcjuHuSfVj24Dwb95t6AWpMI4shoq5BJeyqOxM+wwCHbXajWbN/fPHBF1LPlrhXOQ63KBfRq4K3wuZR3L/McmiiUoB9Y2VZ+vDQkBMDjfcFE9XFIIoRAChzUeqsRZxnGjQbAvISUMWszjalneKm7i8FhgYlZ/skMkT1iv58J8U5oisB1A9GzDiqMMYPIfxTznW0jDX/fxo1y0tNNfDM60F4Mx/97ojl0JXqXIPK9BswfBKmDzYDdx+MJ8vBqVCbHatPLQafTEUVPEJxt663soC+mOoVBc/1Nfuy+3QhmIw7kg58R+8QSorSuKjMatWPmrNUfSXDeWVJAavzfKCHtX+kHdrq1QssREvpLaf5RRD3lmtUYTYn8cxFZ8FKa/tOb5+MlwqOg/XxWH6+jxTsg4wUGMpMzbqICpMBNWuDtg="
    bucket: dsx-server-artifacts
    skip_cleanup: true
    acl: public_read
    local_dir: build
    upload-dir: $TRAVIS_REPO_SLUG
    region: eu-central-1
    on:
      tags: true

services:
  - redis-server

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8
    - rpm

notifications:
  email: false
