dist: trusty
sudo: required

services:
  - docker

env:
  global:
    - RELEASE_VERSION=1.0.0-beta.4
    - BINTRAY_API_KEY:
        secure: "Ny2HHKxitwyJtnTeQI7TDCiVd4hvpsN/j5B8q04ieJHhz/B78TYq5om+5FoeluqC7HZjwiuob08ek6KIhRpbSCW1DCaeJEvSW3p56Ak221ISKyNvJPnAR6Y2M92AhMNVi48KgQfQP8kpXJBoy8r6iTXIP161YyDzYZ5E9HU4itY="

  matrix:
    - DISTRO=centos
      VERSION=7

    - DISTRO=ubuntu
      VERSION=trusty

    - DISTRO=ubuntu
      VERSION=wily

    - DISTRO=ubuntu
      VERSION=xenial

    - DISTRO=debian
      VERSION=jessie

script:
  - chmod +x linux.sh
  - ./linux.sh $DISTRO $VERSION "$RELEASE_VERSION"
