dist: trusty
sudo: required

services:
  - docker

matrix:
  - DISTRO=centos
    VERSION=7

  - DISTRO=ubuntu
    VERSION=trusty

  - DISTRO=ubuntu
    VERSION=wily

  - DISTRO=ubuntu
    VERSION=xenial

  - DISTRO=debian
    VERSION=jessie

script:
  - chmod +x linux.sh
  - ./linux.sh $DISTRO $VERSION
