services:
  - docker

env:
  matrix:
    - DISTRO=centos
      VERSION=7

    - DISTRO=ubuntu
      VERSION=trusty

    - DISTRO=ubuntu
      VERSION=xenial

    - DISTRO=debian
      VERSION=jessie

script:
  - curl -O https://raw.githubusercontent.com/deepstreamIO/deepstream.io/master/scripts/linux-package.sh
  - curl -O https://raw.githubusercontent.com/deepstreamIO/deepstream.io/master/scripts/trigger-build.sh
  - sh linux-package.sh $DISTRO $VERSION

after_script:
  - sh trigger-build.sh releases/test
