sudo: true
language: node_js

before_install:
  - gem install fpm --conservative || echo "FPM install failed"
  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then
      if [ "$CC" == "gcc" ]; then
        export CC=$(ls -t /usr/local/bin/gcc-?.?);
      fi
    fi
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then
      export CXX=g++-4.8;
    fi

compiler:
  - gcc
  - clang

node_js:
  - "8"
  - "6.11"
  - "4"

env:
  - DEFAULT_DELAY: 50

matrix:
  include:
    - node_js: "6.11"
      os: osx

script:
  # This fails on node 4
  - if [[ "$TRAVIS_NODE_VERSION" == "6.11"* ]]; then
      npm run lint;
    fi
  - npm run reporter
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then
      sh scripts/run-e2e.sh;
    fi
  # This has to happen here and not in before_deploy to be put in travis cache
  - bash ./scripts/package.sh

cache:
  directories:
    - nexe_node

deploy:
  - provider: s3
    access_key_id:
      secure: "RfOy7DkJvb93YIRW7mf7qX8IdBHIP8bQci5djrxl5lMQewUJG2lpus6HfOT/MQTYg062PpOw1gNHLVtXMZOcwLuRwsWnywz5qGNK8m8VCeCnVq/AGyXg7MEdTOlzh45MVYyUnCFU/2VvQ0qW4cXXXaPyqNXT5FKyK0JH7WUV9qVJDTr/OiJIAkg66AKP+ilwOmJmrMHk7FMa5Poi3Y+DQfIwkaXpesjDr3pj5+irWUtoioSv9lHE8ciwR9/wDtrhvt7Zl9JYih9hCM/gQTA1tKkbUkBKRsxFdjEGYK3cWIU4ahkQIdpZpcSkpgZR542adubVsC9bKy9ZILt/rwHNBuIUzaCjTlpWii0P6IDu7hrDWPT62GLi1oCOTcX2G+c6eLFEVcBVhP9lFXYOSi7376SB+nXwADevcnlh28jbjrscYx4tvaOJJcNuI0Knyc58OWPxDSCJ8hapvA6b+nYa5zReFBsehnNq42soIbBVjV+gtJU5gdNElB3QMk25z91XGZBWg3n+M+8IuPL6+HRQk3g0F7glFhEk/EovyxvfEyCZQWw4IjYL2b+ICvBG73bn+Mhiae4be5K+rwbNdzWeVQZkJAnrw608RUSHB5WRyaI3LxHmUipmrMUu+W0cHgnV1IaBVeJBeHxofwlJPAhBCPJHC6E8kg8mTow+Wc0C9fo="
    secret_access_key:
      secure: "h7isxH2B4tC5LlfikGWl1E15Kkgz9/6E0Y6BstVd/x4kFFKytnRjcJmT6fcVFeOOXzMMtKt7Nm2A+UVPa2bAxdugx8WxjEjY+NAD7Q2txXuDSF2m+wQTs6+8YmD51goIP/dzyat3wPIcgdXZS6wIMy0+0N+8jVBZ6/qLikL7X0GaeRDX/76S5gkDHiKTP+dAmJB5XsU/HYFqnI8kTF1NBTxa1QzLwiDQ9gmhwp6nFyJzC4KycnqEN77/8W456aH6bFbzLW5Vi8CiQLK/EjM92Nf5r22XuugkbWBQUp56zihr2Tv38rQf53G+JObxQKo3AiAGCE8KhwqK9GYKGsSS0YlPwjzwK1uzNGP6fW3tFurs1g/rMpIMxWbEjZqdB7jLHxU+nkpUzWLlVebMlJUF2ncBozSqGhs02Af15TwYF82oLY8HmYxhQ1/EFt9f/F5Gi9qWcSJkVIiT4zWFlMCq6Z5VsHHAZypJdeMotPgtl+vIfq45zV5UyVneVye3FiiKH2oztlg2PEOQScoYVAZqLs+xd5RZx1TynNmjhFl1FCDj9yCAL3oZznPIMBs6QMCNOHgMLWHUfVfc6B5UE3DKgTgtrV3cnD8t5zmkA0JXgHnetSwdUf/Cs7N8llCam3DysNm9x07hoAfISoAqO9thOHI9srlUoqOR21JiMyarbjY="
    bucket: ds-server-artifacts
    skip_cleanup: true
    acl: public_read
    local_dir: build
    upload-dir: $TRAVIS_REPO_SLUG
    on:
      branch: master
  - provider: s3
    access_key_id:
      secure: "I18K+fcvIuH2qg7eow0PtBC7J5oenf/w3SmmKpCl/Cr7oLcs7Qb92Dbmw/7TCTL5OaRvGyJ7QjaVpFjFhcEoB30WZvyth/qs8oTZb5qSPXQlRepto39Qj5vRef0ICpMgxGHYYCm7fLI+8YMWQgEF4SjKUgxeobo6WYATu+c9aD0c9xJtMFcwQWmtHKhln5ao4A4a0vYPDWz1AGJIiWqpSJjsUNWx6pa5F7UwPT7ZnzA3eKFvJVftgI/aFaowpUhrkrJ57rVjVkKJm30ny/gSc1BT++TdpQGAjwXPZrZsSmLzJjJYA2SEOEA5+D3BfrnI/HjQRWya+zWjkCrX5LOzb2uUU2cRRgtBCYBdLmoopiu373A5HNZ3BkNlXa1qPmUxCkZ2CL19FjXp4sdXDHjyL3qrT+gaWS2KF+w9DsITdVELm9cKMLEppCCrZfA3CRXxZogo8X0hiYqkHcpLNTDKDgRvsoIH9fwgAB8wHUHjwHFev5WQ188Pz1hAaPkWs/vKvOBgO/ykM52ZXF4cF9ewHJ1tcfert5Yvo4rxFxDNZGlMRDZB1zYXJ96oVlyit+7kiwRs/XFD5/zOQP7gklyFCfyQgfR2UoFM0Jwm4RbC2rB1I+MIKCMqQe7+QxeLyUMsYOWasHcsJf8y7L3HDY+UW56GOPywJr6+D5IQuko4SWk="
    secret_access_key:
      secure: "rqiM7mKGiQuyX+0XOHas6j/VdmqKSnXzSE0p/CtWM+CeEE/W5a468GWR+MF+SdLGitHXB/9pEBmvNuJidWdlcdY1IQtbKB15ByetYbBsPI9mITsjqy1i+VUXMc+t7/im89KLjaqSHHbzwd9fKwLWjUbJVyrgxOSxWYM6ZJphBf/6BichRjevPxdifm38mLGfvGR44zkihpFmttaQaOthxwzJ5faClVHqk4zfv+XxVUCDM9vitsAkNsoWzXEsBdBWn3bocC3kTvpPo1cyclHR21iGJwNhaA6oefmyEBfTLCSRdHmwehhm2CGR7FjY8s2KsAe66E4lV9fcnVmEUCu+0GAw+5MurNj8PSYQAYZhu/oKG87Q+Njp6sicPtu0AaNb9D7wkMjUrTbQcFoH4vF0Y5OQl3VRIIc9yj0vBQFMrzHmK9ETSTDXkpB32Xwhm1tVQeb5v7/eJrlHqMxutReHSO4mPsLB8CNWa9wH8VoAtm4mEWp4Ub8TOWPBuT86byuCuT1g3XSeeMhO7DxjtSJsdZfHYaywmhZQg0sp4d/61VGtoDNgLudAw+XB62N+eFEYAtCthPm8vJlOCbhV/La57IXDXt8oWne3peuBkJGtk0WZsL202+geDJeZrBoZ4UXpWcZ8QZ3TN+v8z0MA9Rkqd/W9kfnaIWOXqmI6k8ugP3I="
    bucket: dsx-server-artifacts
    skip_cleanup: true
    acl: public_read
    local_dir: build
    upload-dir: $TRAVIS_REPO_SLUG
    on:
      tags: true

services:
  - redis-server

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8
    - rpm

notifications:
  email: false
